spring.application.name=trustgraph
spring.datasource.url=jdbc:postgresql://localhost:5432/trustgraph
spring.datasource.username=pujasvijella
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update